# Generated by Django 4.1.7 on 2023-02-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="contact",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
