# Generated by Django 4.1.7 on 2023-02-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_driver_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="contact",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
