# Generated by Django 4.1.7 on 2023-02-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
                ("landmark", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                (
                    "loadtype",
                    models.CharField(
                        blank=True,
                        choices=[("h", "High"), ("m", "Medium"), ("l", "Low")],
                        default="l",
                        help_text="Type of Load",
                        max_length=1,
                    ),
                ),
                ("best_route", models.TextField(max_length=1000)),
                (
                    "driveremail",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint", models.TextField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p", "Pending"),
                            ("i", "InProgress"),
                            ("a", "Approved"),
                        ],
                        default="p",
                        help_text="Status",
                        max_length=1,
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="waste.bin",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
    ]
