# Generated by Django 4.2.5 on 2023-10-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_bin_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='price',
        ),
    ]
