# Generated by Django 4.2.5 on 2023-10-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0011_bin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
