# Generated by Django 4.2.5 on 2023-10-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0015_bin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='user',
        ),
    ]
